### ISSUE TITLE
The reports do not arrive

### ISSUE THREAD

**Issue by Jeffrey-kroonenberg** [vipexv/vReports#10]
The reports do not arrive both and with ACE Perms and with Discord rolling
It does

**Comment by vipexv** [comment]
I don't understand what your trying to say, can you explain in more detail with examples and videos along with steps to re-produce?

**Comment by Jeffrey-kroonenberg** [comment]
That is good just can't make Vdieos

I mean that if reports come in that I can't see them
I do see my own reports.
I have arranged Staff Perms via Disocrd Perms>
ACE Perms also brought along does not work unfortunately
