### ISSUE TITLE
REQUEST [feature]

### ISSUE THREAD

**Issue by MrNewb** [vipexv/vReports#2]
Hey awesome work, even more awesome that its open.
Wanted to see if its ok to request a feature?
Idea is player reports that automatically populate the nearest players, ie I get rdmed and dont know who killed me but they are still in proximity I can do /report and itl auto pull the nearest player and maybe imgur/discord integration for screenshots? If not its cool, kinda the point in open code. :) thanks for the release either way dude.

**Comment by vipexv** [comment]
So what i'm thinking is everytime a report is created, we have logic checking of the nearest players within a specific radius and you can see that in the NUI?

**Comment by vipexv** [comment]
Will be getting added in v1.0.1 which will be released shortly.

![image](https://github.com/vipexv/vReports/assets/101529155/a53e8f1d-5c8d-4466-b1f6-3420ca37ec7f)


![image](https://github.com/vipexv/vReports/assets/101529155/12cb75c8-f7ba-46a0-bc87-6ef34e3d865e)
